FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONUNBUFFERED=1

# 실제 주가 크롤링 Producer로 변경
CMD ["python", "-m", "src.kafka.naver_stock_producer"]
